config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views
  root :to => 'welcome#index'
  devise_for :users
  resources :recipes
  resources :comments
  resources :users

  get '/recipes/random', to: 'recipes#random'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# belongs_to :recipe
	# has_one :user
	belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :title, :cuisine, :dish_type, :ingredients, :cooking_steps, :restaurant, presence: true

  validates :dish_type, inclusion: { in: %w(appetizer breakfast lunch dinner supper desert snack Appetizer Breakfast Lunch Dinner Supper Desert Snack APPETIZER BREAKFAST LUNCH DINNER SUPPER DESERT SNACK ), message: "%{value} is not a valid dish type" }

	belongs_to :user
	has_many :comments


  def self.search_for(query)
    where('title LIKE :query OR restaurant LIKE :query OR dish_type LIKE :query' , query: "%#{query}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :recipes
	has_many :comments, dependent: :destroy

end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << [:name, :bio]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new({
			body: params[:comment][:body],
			user_id: current_user.id,
			recipe_id: params[:recipe_id]
			})
  		if @comment.save
  			redirect_to :back
  		else
        render 'new'
  	  end
	end

	def show
    @comment = Comment.find(params[:id])
	end

	def update
	end

	def destroy
		@user = current_user
		@comment = Comment.find(params[:id])
	    @comment.destroy
	    # redirect_to recipes_path
	    redirect_to :back

	end
	

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy] 

	  def index
    @recipes = Recipe.search_for(params[:q])
    @user = current_user
    end

    # def random
    #   @recipe = Recipe.find_by
    # end


  	def new
  	@recipe = Recipe.new
    @user = current_user

  	end

  	def create
        # binding.pry
  	@recipe = Recipe.new(safe_recipe_params)
  		if @recipe.save
  			redirect_to recipes_path
  		else
        render 'new'
  	  end
    end
    
  	def show
    @recipe = Recipe.find(params[:id])
    @comments = @recipe.comments.all
    @comment = @recipe.comments.build
    @comment.recipe_id = params[:id]
    @user = current_user
      # binding.pry
  	end

    def edit
    @recipe = Recipe.find(params[:id])
    end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(title: params["recipe"]["title"], cuisine: params["recipe"]["cuisine"], img_URL: params["recipe"]["img_URL"], dish_type: params["recipe"]["dish_type"], ingredients: params["recipe"]["ingredients"], cooking_steps: params["recipe"]["cooking_steps"], restaurant: params["recipe"]["restaurant"])
    redirect_to recipes_path 
  end

  def destroy
   @recipe = Recipe.find(params[:id])
    @recipe.destroy 
    redirect_to recipes_path
  end

private

    def safe_recipe_params
      params.require('recipe').permit(:title, :img_URL, :cuisine, :dish_type, :ingredients, :cooking_steps, :restaurant).merge(user_id: current_user.id)
    end

    def load_recipe
      @shirt = Recipe.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:notice] = "Invalid Recipe ID #{params[:id]}"
      redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
  	@user = User.new(params.require(:user).permit(:name, :email, :bio, :usr_img))

  		if @user.save
  			redirect_to root_path
  		else
  			render :new
  		end
	end

	def show
		# binding.pry
		@user = current_user
		# @user = User.find(params[:id])
	end

	def edit
	end

	def update
	end

	def destroy
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@user = current_user

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/show.html.erb
		<strong>Comment </strong><%= @comment.id %><br />

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <a class="navbar-brand" href="#">What's The Recipe?</a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">           
 			      <li class="active">
 				       <a href="#">
           		<span class="glyphicon glyphicon-home"></span>
        		  </a>
        	 </li>
            
            <li>
            	<%= link_to 'View Recipes', recipes_path %>
            </li>


              <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, :placeholder => "Email", class: "form-control" %> 
        </div>
        <div class="form-group">
          <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
        </div>
        <!-- <div class="checkbox">
          <%= f.check_box :remember_me %><%= f.label :remember_me %>
        </div> -->
        <%= f.submit 'Login', class: "btn btn-default" %>
        <% end %>

        <% if user_signed_in? %>
          	<li>
				      <%= link_to 'Create Recipe', new_recipe_path %>
			     </li>
            <li>
             <%= link_to 'View Profile', user_path, :method => :get %>
           </li>
			     <li>
			       <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
			     </li>
		    <% end %>
		</li>
		<!-- <li>
			<% if user_signed_in? == false %>
			<%= link_to 'Sign In', new_user_session_path %> 
			</li> -->
			<li>
				<%= link_to 'Sign Up', new_user_registration_path %>
			</li>
			<% end %>
		</li>
    <li> <p class="notice"><%= notice %></p></li>
 <li><p class="alert"><%= alert %></p></li>
		</ul>
        </div><!--/.nav-collapse -->
      </div>

    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whats The Recipe, Find Recipes from your Favorite Restaurants</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<!--  <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p> -->
<%= yield %>

</div>
</body>
</html>

app/views/recipes/_form.html.erb
	<% if @recipe.errors.any? %>
  	<h2>There were errors saving your recipe.</h2>
  	<ul>
    <% @recipe.errors.full_messages.each do |msg| %>
    <strong><%= msg %></strong><br />
    <% end %>
    <% end %>

<%= form_for @recipe do |form| %>
	<div>
	<%= form.label :'Dish Name' %>	<br />
	<%= form.text_field :title %>
	</div>
	<br />
	<div>
	<%= form.label :'Image (web address, including http)'%>	<br />
	<%= form.text_field :img_URL %>
	</div>
	<br />
	<div>
	<%= form.label :Restaurant %>	<br />
	<%= form.text_field :restaurant %>
	</div>
	<br />
	<div>
	<%= form.label :Cuisine %>	<br />
	<%= form.text_field :cuisine %>
	</div>
	<br />
	<div>
	<%= form.label :"Dish Type (Appetizer, Breakfast, Lunch, Dinner, Desert)" %>	<br />
	<%= form.text_field :dish_type%>
	</div>
	<br />
	<div>
	<%= form.label :Ingredients %>	<br />
	<%= form.text_area :ingredients %>
	</div>
	<br />
	<div>
	<%= form.label :Cooking_steps %>	<br />
	<%= form.text_area :cooking_steps %>
	</div><br />
	<% :user_id %>
	<div><%= form.submit %></div>

<% end %>

app/views/recipes/edit.html.erb
<div class="transbox">
<h1>Edit Recipe</h1>
<%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<!--       <div class="container">
 -->        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
 <a class="navbar-brand">
              <%= image_tag "WTRLogo.png", :class => "nav-logo" %>
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
         <li><a href="/">
           <span class="glyphicon glyphicon-home"></span>
        </a></li>
            <li class="active"><%= link_to 'View Recipes', recipes_path %></a></li>
          <% if user_signed_in? %>
          <li>
			<%= link_to 'Create Recipe', new_recipe_path %>
		</li>
    <li>
              <p><%= link_to raw('<span class="glyphicon glyphicon-user"> Profile </span>'), user_path(@user) %></p>
            </li>
		<li>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>		</li>
			<% end %>
		</li>
		<!-- <li>
			<% if user_signed_in? == false %>
			<%= link_to 'Sign In', new_user_session_path %>
			</li> -->	
      <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, :placeholder => "Email", class: "form-control" %> 
        </div>
        <div class="form-group">
          <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
        </div>
        <!-- <div class="checkbox">
          <%= f.check_box :remember_me %><%= f.label :remember_me %>
        </div> -->
        <%= f.submit 'Sign In', class: "btn btn-default" %>
        <% end %>
			 <li> 
			<%= link_to 'Sign Up', new_user_registration_path %>
		</li>
			<% end %>
		</li>
		</ul>
        </div><!--/.nav-collapse -->
      </div>

    </nav>
    <div class="transbox">
      <br />
      <br />
<h1>Recipe Index</h1>

<br />

<%= form_tag "/recipes", method: "GET" do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search Recipes" %>
<% end %>

<% @recipes.each do |recipe| %><br />
	<h3>Dish Name: <%= link_to recipe.title, recipe %><br />
	Restaurant: <%= recipe.restaurant%><br />
	Cuisine: <%= recipe.cuisine %><br /></h3>
<!--     User Id: <%= recipe.user_id %>
 -->	<br />
	<% end %>


	<p><%= link_to 'Home', root_path %></p>
    <p>
        <% if user_signed_in? %>
        <%= link_to 'Add New Recipe', new_recipe_path %>
        <% end %>
    </p> 

</div>

app/views/recipes/new.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
 <a class="navbar-brand">
              <%= image_tag "WTRLogo.png", :class => "nav-logo" %>
            </a>
</div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">
           <span class="glyphicon glyphicon-home"></span>
        </a></li>
            <li><%= link_to 'View Recipes', recipes_path %></a></li>
          <% if user_signed_in? %>
          <li class="active">
			<%= link_to 'Create Recipe', new_recipe_path %>
		</li>
    <li>
              <p><%= link_to raw('<span class="glyphicon glyphicon-user"> Profile </span>'), user_path(@user) %></p>
            </li>
		<li>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>		</li>
			<% end %>
		</li>
		<li>
			<% if user_signed_in? == false %>
			<%= link_to 'Sign In', new_user_session_path %> or 
			<%= link_to 'Sign Up', new_user_registration_path %>
			<% end %>
		</li>


		</ul>
        </div><!--/.nav-collapse -->
      </div>

    </nav>
    <br />
    <br />
        <div class="transbox">
<h1>Create a New Recipe</h1>

<%= render 'form' %>
</div>

app/views/recipes/random.html.erb
		<p>
		<h2><strong>Dish Name: </strong><br />
			<%= @recipe.title %></h2><br />
		<%if @recipe.img_URL? %>
		<img src=<%= @recipe.img_URL %> style="max-width:300px;border-radius:10px;"><br /><br />
		<%end%>
		<strong>As found in: </strong><%= @recipe.restaurant %><br />
		<strong>Cuisine: </strong><%= @recipe.cuisine %><br />
		<strong>Dish Type: </strong><%= @recipe.dish_type %><br /><br />
		<strong>Ingredients: </strong><%= @recipe.ingredients %><br /><br />
		<strong>Cooking Steps: </strong><%= @recipe.cooking_steps %><br /><br />
		</p>

app/views/recipes/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<!--       <div class="container">
 -->       
<div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         
          <a class="navbar-brand">
              <%= image_tag "WTRLogo.png", :class => "nav-logo" %>
            </a>
</div>
        
<div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
        		<li>
        	  		<a href="/">
           			<span class="glyphicon glyphicon-home"></span>
        			</a>
        	  	</li>
            	<li class="active"><%= link_to 'View Recipes', recipes_path %>
            	</li>
        <% if user_signed_in? %>
          		<li>
				<%= link_to 'Create Recipe', new_recipe_path %>
				</li>
				<li>
              <p><%= link_to raw('<span class="glyphicon glyphicon-user"> Profile </span>'), user_path(@user) %></p>
            </li>	
				<li>
				<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
				</li>
		<% end %>
	
				<li>
		<% if user_signed_in? == false %>
				<%= link_to 'Sign In', new_user_session_path %>
				</li>
				<li>
				<%= link_to 'Sign Up', new_user_registration_path %>
				</li>	
		<% end %>
			
		</ul>
</div><!--/.nav-collapse -->
      
</nav>
<div class="transbox">
	<br />
	<br />
   <h2>RECIPE</h2>
<!-- <div class="recipe">
 -->	<p>
		<h2><strong>Dish Name: </strong><br />
			<%= @recipe.title %>
		</h2>
		<br />
		
		<%if @recipe.img_URL? %>
		<img src=<%= @recipe.img_URL %> style="max-width:300px;border-radius:10px;"><br /><br />
		<%end%>




		<strong>As found in: </strong><%= @recipe.restaurant %><br />
		<strong>Cuisine: </strong><%= @recipe.cuisine %><br />
		<strong>Dish Type: </strong><%= @recipe.dish_type %><br /><br />
		<strong>Ingredients: </strong><%= @recipe.ingredients %><br /><br />
		<strong>Cooking Steps: </strong><%= @recipe.cooking_steps %><br /><br />
		</p>
		
		<% if user_signed_in? == false %>
		<%= link_to 'Comment On This Recipe!', new_user_session_path %>
		<% end %>

		<h3>Comments</h3>
		<% @comments.each do |comment| %>
  		<div>
    	<p>"<%= comment.body %>"</p>
<!--     	<strong> - <%= User.find(comment.user_id).email %></strong>
 -->    	<strong> - <%= User.find(comment.user_id).name %></strong>

    	<p>
    		<% if comment.user == current_user  %>
    		<%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    	</p>
    	<% end %>
  		</div>
    	<% end %>


		<% if user_signed_in? %>
		<h3>Comment On This Recipe!</h3>
			<%= form_for @comment do |form| %>
		<div>
			<%= form.label :'Comment' %>	
			<br />
			<%= form.text_area :body %>
		</div>
			<%= hidden_field_tag :recipe_id, @recipe.id %>
			<%= hidden_field_tag :user_id, @user.id %>

		<div><%= form.submit %></div>
		<% end %>
<!-- 		<% end %>
 -->

		<% if user_signed_in? && current_user.id == @recipe.user_id %>
		<%= link_to 'Edit Recipe', edit_recipe_path(@recipe[:id]) %>
		<br />
		<%= link_to 'Delete Recipe', recipe_path(@recipe[:id]), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	
</div>
<!-- </div> -->

app/views/users/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            
             <a class="navbar-brand">
              <%= image_tag "WTRLogo.png", :class => "nav-logo" %>
            </a>
<!--           <a class="navbar-brand" href="#">What's The Recipe?</a>
 -->        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">           
 			      <li class="active">
 				       <a href="/">
           		<span class="glyphicon glyphicon-home"></span>
        		  </a>
        	 </li>
            
            <li>
            	<%= link_to 'View Recipes', recipes_path %>
            </li>



        <% if user_signed_in? %>
            <li>
              <%= link_to 'Create Recipe', new_recipe_path %>
           </li>
            <li>
              <p><%= link_to raw('<span class="glyphicon glyphicon-user"> Profile </span>'), user_path(@user) %></p>
            </li>
           <li>
             <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
           </li>
        <% end %>
    </li>
        <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, :placeholder => "Email", class: "form-control" %> 
        </div>
        <div class="form-group">
          <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
        </div>
        <!-- <div class="checkbox">
          <%= f.check_box :remember_me %><%= f.label :remember_me %>
        </div> -->
        <%= f.submit 'Sign In', class: "btn btn-default" %>
        <% end %>

    <!-- <li>
      <% if user_signed_in? == false %>
      <%= link_to 'Sign In', new_user_session_path %> 
      </li> -->
      <li>
        <%= link_to 'Register', new_user_registration_path %>
      </li>
      <% end %>
    </li>
    <li> <p class="notice"><%= notice %></p></li>
 <li><p class="alert"><%= alert %></p></li>
    </ul>
        </div><!--/.nav-collapse -->
      </div>

    </nav>

        <div class="container theme-showcase" role="main">

<div class="jumbotron">
	<div class="starter-template">
<br />
<br />
    <p>
	<h2>User Name:</h2><br /><%= @user.name %><br />
  <h2>User Email:</h2><%= @user.email %><br />
	<h2>User Bio:</h2><%= @user.bio %>
	</p>

</div>
</div>
</div>

app/views/welcome/index.html.erb
<!--     <div class="container">
 -->    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            
            <a class="navbar-brand">
              <%= image_tag "WTRLogo.png", :class => "nav-logo" %>
            </a>
              <!-- <img src="assets/WTRLogo.png" style="height:100%;margin-right:10px;"/></a> -->
<!--           <a class="navbar-brand" href="#">What's The Recipe?</a>
 -->        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">           
 			      <li class="active">
 				       <a href="/">
           		<span class="glyphicon glyphicon-home"></span>
        		  </a>
        	 </li>
            
            <li>
            	<%= link_to 'View Recipes', recipes_path %>
            </li>



        <% if user_signed_in? %>
            <li>
              <%= link_to 'Create Recipe', new_recipe_path %>
           </li>
            <li>
              <p><%= link_to raw('<span class="glyphicon glyphicon-user"> Profile </span>'), user_path(@user) %></p>
            </li>
           <li>
             <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
           </li>
        <% end %>
    </li>
        <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, :placeholder => "Email", class: "form-control" %> 
        </div>
        <div class="form-group">
          <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
        </div>
        <!-- <div class="checkbox">
          <%= f.check_box :remember_me %><%= f.label :remember_me %>
        </div> -->
        <%= f.submit 'Sign In', class: "btn btn-default" %>
        <% end %>

    <!-- <li>
      <% if user_signed_in? == false %>
      <%= link_to 'Sign In', new_user_session_path %> 
      </li> -->
      <li>
        <%= link_to 'Register', new_user_registration_path %>
      </li>
      <% end %>
    </li>
    <li> <p class="notice"><%= notice %></p></li>
 <li><p class="alert"><%= alert %></p></li>
    </ul>
        </div><!--/.nav-collapse -->
      </div>

    </nav>
    <br />
    <br />
    <div class="container theme-showcase" role="main">

      <div class="jumbotron">

 <a>
              <div><%= image_tag "WTRLogoBlk.png", :class => "nav-logo2" %></div>
            </a>

<br />
        <h2>WhatsTheRecipe.com</h2>
        <h3>The site where cooks like you share "best guess" recipes<br />for dishes from their favorite restaurants!</h3><br />
       <h3>Browse recipes from our growing cooking community...<br /></h3>

        <p><a href="/recipes" class="btn btn-primary btn-lg" role="button">Checkout some Recipes! &raquo;</a></p>
    <!--      <p><a href="/recipes/random" class="btn btn-lg btn-info" role="button">Random Recipe &raquo;</a></p> -->
           
    <% if user_signed_in? == false %>
    <h3>Got the chops?<br />Join today and share your recipes.  <br /></h3>
        <p>
          <%= link_to raw('<span class="btn btn-lg btn-info" role="button"> Join Today ! </span>'), new_user_registration_path(@user) %>
        </p>
        The proof is "in the pudding"<br />(so to speak).
      <% end %>

    </div>
    </div>
<!--   </div>
 -->